# Dependencies
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
pygments:         true

# Permalinks
permalink: /:year/:month/:day/:title

# Setup
title: MorningSYJ
tagline: '醒醒'
description: '关注算法，计算机视觉和其他好玩的东西'
url: http://morningsyj.github.io
domain: morningsyj.github.io
#twitterID: 
#timezone: 
#subscribe: 
exclude: [ README.md, newpost.rb, CNAME ]

author:
  name:           'Yeji Shen'
  url:            http://morningsyj.github.io

paginate:         5

github:
  repo:           https://github.com/morningsyj/morningsyj.github.com
  #githubEditBaseURL: https://github.com/pala/pala.github.com/edit/master/
